bg_dir: raw_images/background/
obj_dir: raw_images/object/

background:
  ddca3f92-4b8e-4672-bb6b-f3594ad4e304.jpg:
    bg_scale: 8.0
    obj_scale: 0.8
    obj_range: [[120,120],  # x1 y1
                [470,450]]  # x2 y2
    bg_weight: 0.6
    obj_weight: 1.3
    gamma: 0.
    crop_shape_range: [1500, 2000]