bg_dir: raw_images/background/
obj_dir: ../../XrayImgGen/images/module/

background:
  ddca3f92-4b8e-4672-bb6b-f3594ad4e304.jpg:
    bg_scale: 8.0
    obj_scale: 1.0
    obj_range: [[120,120],  # x1 y1
                [470,450]]  # x2 y2
    bg_weight: 0.6
    obj_weight: 1.0
    gamma: 0.
    crop_shape_range: [1500, 2000]

  Covid_ches_Xray.webp:
    bg_scale: 3.0
    obj_scale: 0.8
    obj_range: [[430,500],    # x1 y1
                [1100,1000]]  # x2 y2
    bg_weight: 0.9
    obj_weight: 1.0
    gamma: -50
    crop_shape_range: [1500, 2000]

  images.jpeg:
    bg_scale: 13.0
    obj_scale: 0.8
    obj_range: [[70,40],  # x1 y1
                [240,150]]  # x2 y2
    bg_weight: 0.6
    obj_weight: 1.0
    gamma: 0.
    crop_shape_range: [1200, 1800]

  ChestXray.jpg:
    bg_scale: 3.0
    obj_scale: 0.8
    obj_range: [[390,180],  # x1 y1
                [1000,720]]  # x2 y2
    bg_weight: 0.6
    obj_weight: 1.0
    gamma: 0.
    crop_shape_range: [1500, 2000]

  iStock_22401848_MEDIUM-58262cb63df78c6f6adebb27.jpg:
    bg_scale: 3.0
    obj_scale: 0.7
    obj_range: [[450,250],  # x1 y1
                [1050,800]]  # x2 y2
    bg_weight: 0.6
    obj_weight: 1.0
    gamma: 0.
    crop_shape_range: [1000, 1500]

  image-asset.png:
    bg_scale: 3.0
    obj_scale: 0.6
    obj_range: [[270,290],  # x1 y1
                [800,780]]  # x2 y2
    bg_weight: 0.6
    obj_weight: 1.0
    gamma: 0
    crop_shape_range: [900, 1200]